---
apiVersion: opentestfactory.org/v1alpha1
kind: Workflow
metadata:
    name: Robot Execute With Params
    defaults:
        runs-on: ssh
jobs:
    testParamFailure:
        runs-on: ssh
        steps:
        -  uses: action/checkout@v1
           with:
               repository: https://github.com/SquashTF-workshop/robotTFParamCheck
        -  uses: robotframework/params@v1
           with:
               data:
                   test:
                       DSNAME: data
               path: paramfile
               format: tm.squashtest.org/params@v1
        -  uses: robotframework/execute@v1
           with:
               test: robotTFParamCheck/robot_community.robot#Check DS_NAME
    testParamSuccess:
        runs-on: ssh
        needs: testParamFailure
        steps:
        -  uses: action/checkout@v1
           with:
               repository: https://github.com/SquashTF-workshop/robotTFParamCheck
        -  uses: robotframework/params@v1
           with:
               data:
                   test:
                       DSNAME: dataset1
               path: paramfile
               format: tm.squashtest.org/params@v1
        -  uses: robotframework/execute@v1
           with:
               test: robotTFParamCheck/robot_community.robot#Check DS_NAME
